// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/register": {
            "post": {
                "description": "Create a new todo item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RMS"
                ],
                "summary": "Create a RMS",
                "parameters": [
                    {
                        "description": "New User",
                        "name": "RMS",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.Registration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/form.Registration"
                        }
                    }
                }
            }
        },
        "/registerbyemail": {
            "post": {
                "description": "Create a new User by Email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RMS"
                ],
                "summary": "Create a RMS",
                "parameters": [
                    {
                        "description": "New User",
                        "name": "RMS",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.Registration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/form.Registration"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "form.Registration": {
            "type": "object",
            "required": [
                "ConfirmPassword",
                "EmailAddress",
                "FirstName",
                "Password"
            ],
            "properties": {
                "Address": {
                    "type": "string"
                },
                "AddressID": {
                    "type": "integer"
                },
                "ConfirmPassword": {
                    "type": "string"
                },
                "CountryID": {
                    "type": "integer"
                },
                "CountryName": {
                    "type": "string"
                },
                "DefaultAddressID": {
                    "type": "integer"
                },
                "DefaultPhoneID": {
                    "type": "integer"
                },
                "EmailAddress": {
                    "type": "string"
                },
                "EmailID": {
                    "type": "integer"
                },
                "Err": {
                    "type": "string"
                },
                "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "LoginID": {
                    "type": "integer"
                },
                "LoginPassword": {
                    "type": "string"
                },
                "LoginTypeDesc": {
                    "type": "string"
                },
                "LoginTypeID": {
                    "type": "integer"
                },
                "MiddleName": {
                    "type": "string"
                },
                "NumberinInterForm": {
                    "type": "integer"
                },
                "Password": {
                    "type": "string"
                },
                "PhoneNoID": {
                    "type": "integer"
                },
                "PhoneNoTypeDesc": {
                    "type": "string"
                },
                "PhoneNoTypeID": {
                    "type": "integer"
                },
                "PhoneNumber": {
                    "description": "PhoneNumber       string ` + "`" + `json:\"PhoneNumber\" form:\"PhoneNumber\" query:\"PhoneNumber\" validate:\"required\"` + "`" + `",
                    "type": "string"
                },
                "PhonePrefix": {
                    "type": "integer"
                },
                "PostCode": {
                    "type": "integer"
                },
                "RequestKey": {
                    "type": "string"
                },
                "State": {
                    "type": "string"
                },
                "Town": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                },
                "UserName": {
                    "type": "string"
                },
                "UserNameVerified": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:3000",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "RMS Application",
	Description: "This is a Repair Management Application",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
